#!/usr/bin/env python3
import ast
import networkx as nx
import matplotlib.pyplot as plt

"""
usage: ./graph_gen
"""

filename = 'apps.py'
with open(filename, 'r') as fin:
    src = fin.read()
node = ast.parse(src)

class walker(ast.NodeVisitor):
    def __init__(self):
        self.stack = []
        self.graph = nx.Graph()

    def generic_visit(self, stmt):
        node_name = str(stmt)
        parent_name = None
        if self.stack:
            parent_name = self.stack[-1]

        self.stack.append(node_name)
        self.graph.add_node(node_name)

        if parent_name:
            self.graph.add_edge(node_name, parent_name)

        super(self.__class__, self).generic_visit(stmt)
        self.stack.pop()

w = walker()

w.visit(node)
nx.draw(w.graph)

plt.show()
